services:
  mysql:
    image: mysql:8.0
    container_name: library_db_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: exospect
      MYSQL_DATABASE: library_db
      MYSQL_USER: exospect
      MYSQL_PASSWORD: exospect
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
